config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'favorites#home'
  get '/about', to:'favorites#about'
  get '/contact', to:'favorites#contact'

  resources :genres, only: :show
  resources :categories, except: [:index]
  resources :lists do
    get 'search', on: :collection
    resources :links, except: [:index, :show]
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :lists, dependent: :destroy
  validates :title, presence: true, uniqueness: { scope: [:user_id] }
end

app/models/category_user.rb
class CategoryUser < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :lists, dependent: :destroy
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  belongs_to :list
  validates :title, presence: true
  validates :url, presence: true, uniqueness: { scope: [:list_id] }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :genre
  has_many :links, dependent: :destroy
  validates :title, presence: true, uniqueness: { scope: [:category_id] }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :categories, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_many :links, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def new
    @user     = current_user
    @category = @user.categories.new
  end

  def show
    @category   = Category.find(params[:id])
    @lists      = @category.lists
    @first_list = @lists.first
  end

  def create
    @user     = current_user
    @category = @user.categories.new(category_params)

    #Createボタンをクリック
    if params[:commit]
      if @category.save
        redirect_to root_url
      else
        flash[:danger] = "Failed to create"
        render action: "new"
      end
    #Continue to createボタンをクリック
    elsif params[:next_button]
      if @category.save
        @category = @user.categories.new
        flash[:success] = "Successful creation"
        render action: "new"
      else
        flash[:danger] = "Failed to create"
        render action: "new"
      end
    else
      flash[:danger] = "Failed to create"
      render action: "new"
    end
  end

  def edit
  end

  def destroy
  end

  def update
  end

  def destroy
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!, except: [:home, :about, :contact]

  def home
    if user_signed_in?
      @user           = current_user
      @categories     = @user.categories.order('title ASC')
      if @categories.present?
        @first_category = @categories.first
        @lists          = @first_category.lists
        @first_list     = @lists.first
      end
    else
    end
  end

  def about
  end

  def contact
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def show
    @lists = List.all
    @genre = Genre.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = current_user
    @link = Link.new
    @list = List.find(params[:list_id])
    @links = @list.links.new
    @lists = @user.lists
  end

  def create
    @user = current_user
    @link = @user.links.new(link_params)

    #Createボタンをクリック
    if params[:commit]
      if @link.save
        redirect_to root_url
      else
        flash[:danger] = "Failed to create"
        @link = Link.new
        @list = List.find(params[:list_id])
        @links = @list.links.new
        @lists = @user.lists
        render action: "new"
      end
    #Continue to createボタンをクリック
    elsif params[:next_button]
      if @link.save
        @link = Link.new
        @list = List.find(params[:list_id])
        @links = @list.links.new
        @lists = @user.lists
        flash[:success] = "Successful creation"
        render action: "new"
      else
        flash[:danger] = "Failed to create"
        @link = Link.new
        @list = List.find(params[:list_id])
        @links = @list.links.new
        @lists = @user.lists
        render action: "new"
      end
    else
      flash[:danger] = "Failed to create"
      @link = Link.new
      @list = List.find(params[:list_id])
      @links = @list.links.new
      @lists = @user.lists
      render action: "new"
    end

  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def link_params
    params.require(:link).permit(:title, :url, :list_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]

  def index
    @lists = List.all
    @genres = Genre.all
  end

  def new
    @user       = current_user
    @list       = List.new
    @categories = @user.categories
    @genres = Genre.all
  end

  def show
    @list       = List.find(params[:id])
    @links      = @list.links
    @category   = Category.find(@list.category_id)
  end

  def create
    @user = current_user
    @list = @user.lists.new(list_params)

    #Createボタンをクリック
    if params[:commit]
      if @list.save
        redirect_to root_url
      else
        flash[:danger] = "Failed to create"
        @list = List.new
        @categories = @user.categories
        render action: "new"
      end
    #Continue to createボタンをクリック
    elsif params[:next_button]
      if @list.save
        @list = List.new
        @categories = @user.categories
        flash[:success] = "Successful creation"
        render action: "new"
      else
        flash[:danger] = "Failed to create"
        @list = List.new
        @categories = @user.categories
        render action: "new"
      end
    else
      flash[:danger] = "Failed to create"
      @list = List.new
      @categories = @user.categories
      render action: "new"
    end
  end

  def destroy
  end

  def edit
  end

  def update
  end

  def search
  end

private

  def list_params
    params.require(:list).permit(:title, :description, :category_id, :genre_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :show

  def show
    @user = User.find(params[:id])
    @categories = @user.categories.order('title ASC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  def full_title(page_title)
    base_title = "Favoris"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/categories/new.html.haml
- provide(:title, "Category create")
- breadcrumb :new_category

.container
  .row
    .col-sm-2
    .col-sm-8
      .form-group
        - flash.each do |message_type, message|
          %p.alert{class: "alert-#{message_type}"}
            = message
        %h1 カテゴリ作成
        = form_for(@category) do |f|
          = f.label :title
          = f.text_area :title, class: "field form-control", rows: "1", maxlength: "20", placeholder: "Create category"
          = f.submit "Create", class: "btn btn-primary"
          = f.submit "Continue to create", name: "next_button", class: "btn btn-primary"
    .col-sm-2

app/views/categories/show.html.haml
- provide(:title, "Category")
- breadcrumb :show_category, @category

.container
  .row
    .col-sm-2
      = link_to new_category_path do
        Add
        .fa.fa-plus-square-o
      %ul.list-group
        = link_to root_path do
          %li.list-group-item
            =@category.title
    .col-sm-3
      = link_to new_list_path do
        Add
        .fa.fa-plus-square-o
      %ul.list-group
        - @lists.each do |list|
          = link_to list_path(list) do
            %li.list-group-item
              =list.title

    .col-sm-7
      -if @first_list.present?
        = link_to new_list_link_path(@first_list) do
          Add
          .fa.fa-plus-square-o
        %ul.list-group
          - @first_list.links.each do |list|
            .col-sm-6
              %li
                =link_to "#{list.title}", "#{list.url}", target: "_blank"

app/views/favorites/about.html.haml
- provide(:title, "About")
- breadcrumb :about

%nav.navbar.navbar-expand-xl.navbar-dark.bg-dark
  %a.navbar-brand{:href => "#"} Expand at xl
  %button.navbar-toggler.collapsed{"aria-controls" => "navbarsExample06", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarsExample06", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarsExample06.navbar-collapse.collapse{:style => ""}
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => "#"}
          Home
          %span.sr-only (current)
      %li.nav-item
        %a.nav-link{:href => "#"} Link
      %li.nav-item
        %a.nav-link.disabled{:href => "#"} Disabled
      %li.nav-item.dropdown
        %a#dropdown06.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "http://example.com"} Dropdown
        .dropdown-menu{"aria-labelledby" => "dropdown06"}
          %a.dropdown-item{:href => "#"} Action
          %a.dropdown-item{:href => "#"} Another action
          %a.dropdown-item{:href => "#"} Something else here
    %form.form-inline.my-2.my-md-0
      %input.form-control{:placeholder => "Search", :type => "text"}/

app/views/favorites/contact.html.haml
- provide(:title, "Contact")
- breadcrumb :contact

%ul
  %li
    %form.form-inline
      %input.form-control.mr-sm-2{"aria-label" => "Search", placeholder: "Search", :type => "text"}/
      = button_tag type: "submit", class: "button btn btn-outline-success my-2 my-sm-0" do
        %i.fa.fa-search

app/views/favorites/home.html.haml
- provide(:title, "Home")
- breadcrumb :root

.container
  .row
    -if user_signed_in?
      .col-sm-2
        = link_to new_category_path do
          Add
          .fa.fa-plus-square-o
        -if @categories.present?
          %ul.list-group
            - @categories.each do |category|
              = link_to category_path(category) do
                %li.list-group-item
                  =category.title
      .col-sm-3
        -if @categories.present?
          = link_to new_list_path do
            Add
            .fa.fa-plus-square-o
          %ul.list-group
            - @lists.each do |list|
              = link_to list_path(list) do
                %li.list-group-item
                  =list.title

      .col-sm-7
        -if @first_list.present?
          = link_to new_list_link_path(@first_list) do
            Add
            .fa.fa-plus-square-o
          %ul.list-group
            - @first_list.links.each do |list|
              .col-sm-6
                %li
                  =link_to "#{list.title}", "#{list.url}", target: "_blank"

app/views/genres/show.html.haml
- provide(:title, "Show")
- breadcrumb :show_genre, @genre

.container
  .row
    .col-sm-2.hidden-xs
      %h4 Tab
      .list-group
        %button.list-group-item.list-group-item-action{:type => "button"}
          tab1
        %button.list-group-item.list-group-item-action{:type => "button"} tab2
        %button.list-group-item.list-group-item-action{:type => "button"} tab3
        %button.list-group-item.list-group-item-action{:type => "button"} tab4
        %button.list-group-item.list-group-item-action{:type => "button"} tab5
        %button.list-group-item.list-group-item-action{:type => "button"} tab6
        %button.list-group-item.list-group-item-action{:type => "button"} tab7
        %button.list-group-item.list-group-item-action{:type => "button"} tab8
        %button.list-group-item.list-group-item-action{:type => "button"} tab9
        %button.list-group-item.list-group-item-action{:type => "button"} tab10

    .col-sm-10
      .jumbotron
        %h4= @genre.name
        %small.text-muted.hidden-xs= @genre.description
        %ul.list-group
          - @genre.lists.each do |list|
            %li
              =link_to list_path(list) do
                %h5=list.title
                .small=list.description

app/views/links/create.html.haml
%h1 Links#create
%p Find me in app/views/links/create.html.haml

app/views/links/destroy.html.haml
%h1 Links#destroy
%p Find me in app/views/links/destroy.html.haml

app/views/links/edit.html.haml
%h1 Links#edit
%p Find me in app/views/links/edit.html.haml

app/views/links/new.html.haml
- provide(:title, "Links create")
- breadcrumb :new_link, @list

.container
  .row
    .col-sm-2
    .col-sm-8
      .form-group
        - flash.each do |message_type, message|
          %p.alert{class: "alert-#{message_type}"}
            = message
        %h1 リンク追加
        = form_for [@list, @link] do |f|
          = f.label :List
          %br
          = f.collection_select(:list_id, @lists, :id, :title, {class: "field form-control"})
          %br
          = f.label :title
          = f.text_area :title, class: "field form-control", rows: "1", maxlength: "30", placeholder: "Link title"
          = f.label :url
          = f.url_field :url, class: "field form-control", placeholder: "http://..."
          %br
          = f.submit "Create", class: "btn btn-primary"
          = f.submit "Continue to create", name: "next_button", class: "btn btn-primary"
    .col-sm-2

app/views/links/update.html.haml
%h1 Links#update
%p Find me in app/views/links/update.html.haml

app/views/lists/index.html.haml
- provide(:title, "Index")
- breadcrumb :lists

.container
  .row
    .col-sm-2.hidden-xs
      %h4 Tab
      .list-group
        %button.list-group-item.list-group-item-action{:type => "button"}
          tab1
        %button.list-group-item.list-group-item-action{:type => "button"} tab2
        %button.list-group-item.list-group-item-action{:type => "button"} tab3
        %button.list-group-item.list-group-item-action{:type => "button"} tab4
        %button.list-group-item.list-group-item-action{:type => "button"} tab5
        %button.list-group-item.list-group-item-action{:type => "button"} tab6
        %button.list-group-item.list-group-item-action{:type => "button"} tab7
        %button.list-group-item.list-group-item-action{:type => "button"} tab8
        %button.list-group-item.list-group-item-action{:type => "button"} tab9
        %button.list-group-item.list-group-item-action{:type => "button"} tab10

    .col-sm-10
      -@genres.each do |genre|
        .col-sm-6
          .jumbotron
            =link_to genre_path(genre) do
              %h4= genre.name
            %small.text-muted.hidden-xs= genre.description
            %ul.list-group
              - genre.lists.each do |list|
                %li
                  =link_to "#{list.title}", list_path(list)

app/views/lists/new.html.haml
- provide(:title, "List create")
- breadcrumb :new_list


.container
  .row
    .col-sm-2
    .col-sm-8
      .form-group
        - flash.each do |message_type, message|
          %p.alert{class: "alert-#{message_type}"}
            = message
        %h1 リスト作成
        = form_for(@list) do |f|
          = f.label :Genre
          %br
          = f.collection_select(:genre_id, @genres, :id, :name, {class: "field form-control"})
          %br
          = f.label :Category
          %br
          = f.collection_select(:category_id, @categories, :id, :title, {class: "field form-control"})
          %br
          = f.label :title
          = f.text_field :title, class: "field form-control", rows: "1", maxlength: "20", placeholder: "title"
          = f.label :Description
          = f.text_field :description, class: "field form-control", rows: "3", maxlength: "140", placeholder: "Let me explain"
          = f.submit "Create", class: "btn btn-primary"
          = f.submit "Continue to create", name: "next_button", class: "btn btn-primary"
    .col-sm-2

app/views/lists/search.html.haml
- provide(:title, "Search")
- breadcrumb :search_list

app/views/lists/show.html.haml
- provide(:title, "Show")
- breadcrumb :show_list, @list

.container
  .row
    .col-sm-2
      = link_to new_category_path do
        Add
        .fa.fa-plus-square-o
      %ul.list-group
        = link_to category_path(@category) do
          %li.list-group-item
            =@category.title
    .col-sm-3
      = link_to new_list_path do
        Add
        .fa.fa-plus-square-o
      %ul.list-group
        %li.list-group-item
          %p=@list.title
          %p=@list.description

    .col-sm-7
      = link_to new_list_link_path(@list) do
        Add
        .fa.fa-plus-square-o
      %ul.list-group
        - @links.each do |list|
          .col-sm-6
            %li
              =link_to "#{list.title}", "#{list.url}", target: "_blank"

app/views/users/show.html.haml
- provide(:title, @user.nickname)
- breadcrumb :show_user, @user

.container
  .row
    .col-sm-2
      -if current_user?(@user)
        = link_to new_category_path do
          Add
        .fa.fa-plus-square-o
      #myCategory.list-group{:role => "tablist"}
        - @categories.each_with_index do |category, i|
          %a.list-group-item.list-group-item-action{"data-toggle" => "list", :href => "#list#{i}", :role => "tab"}
            = category.title
    .col-sm-10
      -if current_user?(@user)
        = link_to new_list_path do
          Add
        .fa.fa-plus-square-o
      .tab-content
        - @categories.each_with_index do |category, i|
          .tab-pane{:id => "list#{i}", :role => "tabpanel", class: "#{'active' if i == 0}"}
            .list-group
              - category.lists.each do |list|
                .col-sm-3
                  = link_to list_path(list) do
                    %button.list-group-item.list-group-item-action{:type => "button"}
                      %h4=list.title
                      %p=list.description