config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'favorites#home'
  get '/about', to:'favorites#about'
  get '/contact', to:'favorites#contact'

  resources :genres, only: :show
  resources :categories, except: [:index]
  resources :lists do
    get 'search', on: :collection
    resources :links, except: [:index, :show]
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :lists, dependent: :destroy
  validates :title, presence: true, uniqueness: { scope: [:user_id] }
end

app/models/category_user.rb
class CategoryUser < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :lists, dependent: :destroy
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  belongs_to :list
  validates :title, presence: true
  validates :url, presence: true, uniqueness: { scope: [:list_id] }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :genre
  has_many :links, dependent: :destroy
  validates :title, presence: true, uniqueness: { scope: [:category_id] }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :categories, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_many :links, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def new
    @user     = current_user
    @category = @user.categories.new
  end

  def show
    @category   = Category.find(params[:id])
    @lists      = @category.lists
    @first_list = @lists.first
  end

  def create
    @user     = current_user
    @category = @user.categories.new(category_params)

    #Createボタンをクリック
    if params[:commit]
      if @category.save
        redirect_to root_url
      else
        flash[:danger] = "Failed to create"
        render action: "new"
      end
    #Continue to createボタンをクリック
    elsif params[:next_button]
      if @category.save
        @category = @user.categories.new
        flash[:success] = "Successful creation"
        render action: "new"
      else
        flash[:danger] = "Failed to create"
        render action: "new"
      end
    else
      flash[:danger] = "Failed to create"
      render action: "new"
    end
  end

  def edit
  end

  def destroy
  end

  def update
  end

  def destroy
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!, except: [:home, :about, :contact]

  def home
    if user_signed_in?
      @user           = current_user
      @categories     = @user.categories.order('title ASC')
      if @categories.present?
        @first_category = @categories.first
        @lists          = @first_category.lists
        @first_list     = @lists.first
      end
    else
    end
  end

  def about
  end

  def contact
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def show
    @lists = List.all
    @genre = Genre.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = current_user
    @link = Link.new
    @list = List.find(params[:list_id])
    @links = @list.links.new
    @lists = @user.lists
  end

  def create
    @user = current_user
    @link = @user.links.new(link_params)

    #Createボタンをクリック
    if params[:commit]
      if @link.save
        redirect_to root_url
      else
        flash[:danger] = "Failed to create"
        @link = Link.new
        @list = List.find(params[:list_id])
        @links = @list.links.new
        @lists = @user.lists
        render action: "new"
      end
    #Continue to createボタンをクリック
    elsif params[:next_button]
      if @link.save
        @link = Link.new
        @list = List.find(params[:list_id])
        @links = @list.links.new
        @lists = @user.lists
        flash[:success] = "Successful creation"
        render action: "new"
      else
        flash[:danger] = "Failed to create"
        @link = Link.new
        @list = List.find(params[:list_id])
        @links = @list.links.new
        @lists = @user.lists
        render action: "new"
      end
    else
      flash[:danger] = "Failed to create"
      @link = Link.new
      @list = List.find(params[:list_id])
      @links = @list.links.new
      @lists = @user.lists
      render action: "new"
    end

  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def link_params
    params.require(:link).permit(:title, :url, :list_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]

  def index
    @lists = List.all
    @genres = Genre.all
  end

  def new
    @user       = current_user
    @list       = List.new
    @categories = @user.categories
    @genres = Genre.all
  end

  def show
    @list       = List.find(params[:id])
    @links      = @list.links
    @category   = Category.find(@list.category_id)
  end

  def create
    @user = current_user
    @list = @user.lists.new(list_params)

    #Createボタンをクリック
    if params[:commit]
      if @list.save
        redirect_to root_url
      else
        flash[:danger] = "Failed to create"
        @list = List.new
        @categories = @user.categories
        render action: "new"
      end
    #Continue to createボタンをクリック
    elsif params[:next_button]
      if @list.save
        @list = List.new
        @categories = @user.categories
        flash[:success] = "Successful creation"
        render action: "new"
      else
        flash[:danger] = "Failed to create"
        @list = List.new
        @categories = @user.categories
        render action: "new"
      end
    else
      flash[:danger] = "Failed to create"
      @list = List.new
      @categories = @user.categories
      render action: "new"
    end
  end

  def destroy
  end

  def edit
  end

  def update
  end

  def search
  end

private

  def list_params
    params.require(:list).permit(:title, :description, :category_id, :genre_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :show

  def show
    @user = User.find(params[:id])
    @categories = @user.categories.order('title ASC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  def full_title(page_title)
    base_title = "Favoris"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/_breadcrumb.html.haml
.container
      %p= breadcrumbs separator: " &rsaquo; "

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    %p.text-muted Place sticky footer content here.

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "true", "data-target" => "#navbar", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to "Favoris", root_path, class: "navbar-brand"
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li
          = link_to root_path do
            %i.fa.fa-home
            Home
        %li
          = link_to  lists_path do
            %i.fa.fa-list
            Lists
      %ul.nav.navbar-nav.navbar-right
        %li.btn-group
          %a.dropdown{"aria-expanded" => "false", "data-toggle" => "dropdown", :role => "button"}
            %i.fa.fa-search
            Search
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li{:role => "presentation"}
              =link_to "人気タグ", "#"
            %li{:role => "presentation"}
              =link_to "人気リスト",  lists_path
        - if user_signed_in?
          %li.btn-group
            %a.dropdown{"aria-expanded" => "false", "data-toggle" => "dropdown", :role => "button"}
              %i.fa.fa-plus
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li{:role => "presentation"}
                =link_to "カテゴリ作成", new_category_path
              %li{:role => "presentation"}
                =link_to "リスト作成", new_list_path
              %li{:role => "presentation"}
                =link_to "リンク追加","#"
        - if user_signed_in?
          %li.btn-group
            %a.dropdown{"aria-expanded" => "false", "data-toggle" => "dropdown", :role => "button"}
              %i.fa.fa-user
              User
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li{:role => "presentation"}
                =link_to "マイページ", user_path(current_user)
              %li{:role => "presentation"}
                =link_to "お気に入り", "#"
              %li{:role => "presentation"}
                =link_to "セッティング", edit_user_registration_path
              %li.divider
              %li{:role => "presentation"}
                =link_to "ログアウト", destroy_user_session_path, method: :delete
        -else
          %li.btn-group
            %a.dropdown{"aria-expanded" => "false", "data-toggle" => "dropdown", :role => "button"}
              %i.fa.fa-user-plus
              会員登録
            %ul.dropdown-menu{:role => "menu"}
              %li{:role => "presentation"}
                =link_to "ログイン", new_user_session_path
              %li{:role => "presentation"}
                =link_to "新規登録", new_user_registration_path

app/views/layouts/_rails_default.html.haml
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
= favicon_link_tag "", type: "image/png"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = full_title(yield(:title))
  = render 'layouts/rails_default'
  %body
    = render 'layouts/header'
    = render 'layouts/breadcrumb'
    = yield
    = render 'layouts/footer'
    = debug(params) if Rails.env.development?